/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Objetos.usuario;
import bd.ConexionBD;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmAutenticacion extends javax.swing.JFrame {

    /**
     * Creates new form frmAutenticacion
     */
    public frmAutenticacion() {
        initComponents();
        
        try{
            BufferedImage candado = ImageIO.read(new File("src/icons/candado_peq.png"));
            icono_candado.setIcon(new ImageIcon(candado));
        }catch (IOException e){}
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btIngresar = new javax.swing.JButton();
        icono_candado = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        pfClave = new javax.swing.JPasswordField();
        btLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticación - JUBA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 25, -1, -1));

        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 56, -1, -1));

        btIngresar.setText("Ingresar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 167, 94, -1));
        getContentPane().add(icono_candado, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, 72, 73));
        getContentPane().add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 22, 120, -1));
        getContentPane().add(pfClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 53, 120, -1));

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 167, 87, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:        
        String cuenta = tfUsuario.getText();
        String clave = String.valueOf(pfClave.getPassword());
        
        ConexionBD c = new ConexionBD();
        try {
            c.conectar();
            usuario u = new usuario(cuenta, clave);
            if(c.esUsuarioValido(u)){
                //olvidar clave  de usuario activo en sistema
                u = c.obtenerDatosUsuario(tfUsuario.getText());
                JOptionPane.showMessageDialog(null,"Bienvenido "+u.getNombres()+" "+u.getApellidos()+".","Autenticación",JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Usuario correcto");
                //cargando datos del usuario autenticado
                frmSeleccionarEmpresas se = new frmSeleccionarEmpresas(u);
                se.setVisible(true);
                this.dispose();
                u.setClave(null);
            }else{
                JOptionPane.showMessageDialog(null,"Usuario o Clave Incorrectos","Autenticación",JOptionPane.ERROR_MESSAGE);                        
                System.out.println("Usuario o clave incorrecto");
                limpiar();
            }
            c.desconectar();
        }catch (Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btIngresarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void limpiar(){
        tfUsuario.setText("");
        pfClave.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JLabel icono_candado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pfClave;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
