package Formularios;

import static Formularios.frmBuscarUsuarioEmpresas.tbusuarios;
import Objetos.usuario;
import bd.ConexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerson Junqui
 */
public class frmBuscarIdEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form frmBuscarIdEmpresa
     */
    public frmBuscarIdEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbConsultar = new javax.swing.JButton();
        tfDescripcion = new javax.swing.JTextField();
        Lista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbId = new javax.swing.JTable();
        cbSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbConsultar.setForeground(new java.awt.Color(255, 0, 0));
        cbConsultar.setText("CONSULTAR");
        cbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(cbConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        getContentPane().add(tfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 30));

        Lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE" }));
        getContentPane().add(Lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, 30));

        tbId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Empresa", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbId);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 440, 110));

        cbSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSeleccionar.setForeground(new java.awt.Color(255, 0, 0));
        cbSeleccionar.setText("SELECCIONAR");
        getContentPane().add(cbSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("BUSCAR ID EMPRESAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 290, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/autenticacion.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 0, 920, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean formularioConsultaValido(){
        String tipo = Lista.getSelectedItem().toString();
        String descripcion = tfDescripcion.getText();
        if(tipo.equals("Id Empresa") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar un ID","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Nombre") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar un Nombre","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }
        return true;
    }
    
    public void consultarRegistroE(){
        String tipo = Lista.getSelectedItem().toString();
        String descripcion = tfDescripcion.getText();
        
        //consultar
        try{
            //cunsolta a la base
            try{
                ConexionBD c = new ConexionBD();
                c.conectar();
                
                ArrayList<usuario> registro = c.consultarUsuarios("","usuario");
                ArrayList<usuario> resultado = new ArrayList<usuario>();
                
                //Consultar tipo y descripcion
                if (tipo.equals("Todos")){
                        resultado = registro;
                }else{
                    for (usuario us:registro){
                        if(tipo.equals("Cedula")&&(descripcion.length()>0)){
                            if(us.getCedula().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Nombres")&&(descripcion.length()>0)){
                            if(us.getNombres().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Apellidos")&&(descripcion.length()>0)){
                            if(us.getApellidos().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Cuenta")&&(descripcion.length()>0)){
                            if(us.getCuenta().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Correo")&&(descripcion.length()>0)){
                            if(us.getCorreo().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Id")&&(descripcion.length()>0)){
                            if(String.valueOf(us.getId()).equals(descripcion)){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Tipo")&&(descripcion.length()>0)){
                            if(us.getTipo().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Cargo")&&(descripcion.length()>0)){
                            if(us.getCorreo().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else if(tipo.equals("Estado")&&(descripcion.length()>0)){
                            if(us.getEstado().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(us);
                            }
                        }else{
                            JOptionPane.showMessageDialog(this,"Descripcion vacia.","Consulta Invalida",JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                    }
                }
                
                DefaultTableModel dtm = (DefaultTableModel)tbusuarios.getModel();
                dtm.setRowCount(0);
                
                //recorriendo base de datos for
                for (usuario u:resultado){
                    Object[] fila = new Object[9];
                    fila[0] = u.getId();
                    fila[1] = u.getCuenta();
                    fila[2] = u.getCedula();
                    fila[3] = u.getNombres();
                    fila[4] = u.getApellidos();
                    fila[5] = u.getCorreo();
                    fila[6] = u.getTipo();
                    fila[7] = u.getCargo();
                    fila[8] = u.getEstado();
                    dtm.addRow(fila);
                }
            c.desconectar();
            }catch (Exception e){
                System.out.println("error al consultar usuarios"+e);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los registros","Consulta",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }
    
    private void cbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConsultarActionPerformed
        if (formularioConsultaValido()){
            consultarRegistroE();
        }
    }//GEN-LAST:event_cbConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Lista;
    private javax.swing.JButton cbConsultar;
    private javax.swing.JButton cbSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbId;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
