package Formularios;

import static Formularios.frmIngresoNuevaPiscina.ingresar_id_producto;
import Objetos.producto;
import bd.ConexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerson Junqui
 */
public class frmBuscarIdProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmBuscarIdPiscina
     */
    public frmBuscarIdProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfdescripcion = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        cbSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("BUSCAR ID PRODUCTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 290, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 610, 10));

        cbTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Producto", "Nombre", "Nombre Cientifico", "Proveedor", "Peso Ideal" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("UBICACIÓN:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, 30));
        getContentPane().add(tfdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 220, 30));

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(255, 0, 0));
        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 150, 30));

        cbSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSeleccionar.setForeground(new java.awt.Color(255, 0, 0));
        cbSeleccionar.setText("SELECCIONAR");
        cbSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(cbSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 190, 40));

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre", "Nombre Cientifico", "Proveedor", "Peso Ideal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 680, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/autenticacion.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean formularioValido(){
        String tipo = cbTipo.getSelectedItem().toString();
        String descripcion = tfdescripcion.getText();
        if(tipo.equals("Id Producto") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el Id producto","Consulta",JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(tipo.equals("Nombre") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar un nombre","Consulta",JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(tipo.equals("Nombre Cientifico") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el nombre cientifico","Consulta",JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(tipo.equals("Proveedor") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el proveedor","Consulta",JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(tipo.equals("Peso Ideal") && descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar el peso ideal","Consulta",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    public void consultarRegistro(){
        String tipo = cbTipo.getSelectedItem().toString();
        String descripcion = tfdescripcion.getText();        
        //consultar
        try{
            //cunsolta a la base
            try{
                ConexionBD c = new ConexionBD();
                c.conectar();
                ArrayList<producto> registro = c.consultarProductos("","producto");
                ArrayList<producto> resultado = new ArrayList<producto>();
                //Consultar tipo y descripcion
                if (tipo.equals("Todos")){
                        resultado = registro;
                }else{
                    for (producto emp:registro){
                        if(tipo.equals("Id Producto")&&(descripcion.length()>0)){
                            if(String.valueOf(emp.getId_producto()).equals(descripcion)){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Nombre")){
                            if(emp.getNombre().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Nombre Cientifico")){
                            if(emp.getNombre_cientifico().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Proveedor")){
                            if(emp.getProveedor().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Peso Ideal")){
                            if(String.valueOf(emp.getPeso_ideal()).equals(descripcion)){
                                resultado.add(emp);
                            }
                        }else{
                            JOptionPane.showMessageDialog(this,"Descripcion vacia.","Consulta Invalida",JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                    }
                }

                DefaultTableModel dtm = (DefaultTableModel)tbResultado.getModel();
                dtm.setRowCount(0);
                
                //recorriendo base de datos
                for (producto em:resultado){
                    Object[] fila = new Object[5];
                    fila[0] = em.getId_producto();
                    fila[1] = em.getNombre();
                    fila[2] = em.getNombre_cientifico();
                    fila[3] = em.getProveedor();
                    fila[4] = em.getPeso_ideal();
                    dtm.addRow(fila);
                }
            c.desconectar();
            }catch (Exception e){
                System.out.println("error al consultar producto"+e);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar productos","Consulta",JOptionPane.ERROR_MESSAGE);
            System.out.println("consulta de registros productos: "+e);
        }
    }
    
    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        if (formularioValido()){
            consultarRegistro();
        }
    }//GEN-LAST:event_btConsultarActionPerformed

    private boolean seleccionValida(){ 
        int n = tbResultado.getSelectedRowCount();
        if(n==0){
            JOptionPane.showMessageDialog(this,"Debe seleccionar mínimo un registro","Productos",JOptionPane.ERROR_MESSAGE);
            return false;        
        }
        return true;
    }
    
    private void cbSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeleccionarActionPerformed
        if(seleccionValida()){
            int[] filas = tbResultado.getSelectedRows();
            int col = 0;
            try{
                for(int i=0;i<filas.length;i++){
                    frmIngresoNuevaPiscina.ingresar_id_producto = (int) tbResultado.getValueAt(filas[i],col);
                    frmIngresoNuevaPiscina.tf_Id_empresa.setText(String.valueOf(ingresar_id_producto));
                    System.out.println(ingresar_id_producto);
                }this.dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Ocurrió un error en la selección del id usuario!","Eliminación",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton cbSeleccionar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbResultado;
    private javax.swing.JTextField tfdescripcion;
    // End of variables declaration//GEN-END:variables
}
