package Formularios;

import Objetos.usuario;
import javax.swing.JOptionPane;
import bd.ConexionBD;
import java.sql.Date;

/**
 *
 * @author Jerson Junqui
 */
public class frmCuenta extends javax.swing.JFrame {

    /**
     * Creates new form frmCuenta
     * @param u
     */
    public frmCuenta(usuario u) {
        initComponents();
        
        tfid.setText(String.valueOf(u.getId()));
        tfnombres.setText(u.getNombres());
        tfapellidos.setText(u.getApellidos());
        tfcedula.setText(u.getCedula());
        tfedad.setText(String.valueOf(u.getEdad()));
        tfdireccion.setText(u.getDireccion());
        tftelefono.setText(u.getTelefono());
        tfcelular.setText(u.getCelular());
        tfcorreo.setText(u.getCorreo());
        cbsexo.setSelectedItem(u.getSexo());
        cbTipo.setSelectedItem(u.getTipo());
        cbCargo.setSelectedItem(u.getCargo());
        tffechainicio.setText(u.getFecha_inicio().toString());
        tfcuenta.setText(u.getCuenta());
        cbEstado.setSelectedItem(u.getEstado());
        tfClave.setText(u.getClave());
        System.out.println("Usuario Actual: "+u.getNombres()+" "+u.getApellidos());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfid = new javax.swing.JFormattedTextField();
        tfnombres = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfcedula = new javax.swing.JFormattedTextField();
        tfapellidos = new javax.swing.JFormattedTextField();
        tfedad = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdireccion = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        tftelefono = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfcelular = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        cbsexo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfcorreo = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        tffechainicio = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfcuenta = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbLimpiar = new javax.swing.JButton();
        cbGuardar = new javax.swing.JButton();
        cbSalir = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        cbCargo = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        cbCambiar = new javax.swing.JButton();
        tfClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 0));
        jLabel15.setText("EDITAR USUARIO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 340, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 610, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("ID Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 120, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Nombres");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, 20));

        tfid.setEditable(false);
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 80, 30));
        getContentPane().add(tfnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Apellidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Cedula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 110, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Edad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 20));
        getContentPane().add(tfcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 170, 30));
        getContentPane().add(tfapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 170, 30));
        getContentPane().add(tfedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Direccion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 110, 20));
        getContentPane().add(tfdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Telefono Local");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 160, 30));
        getContentPane().add(tftelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Telefono Movil");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 170, 20));
        getContentPane().add(tfcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText("Sexo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 80, 30));

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        getContentPane().add(cbsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 0));
        jLabel13.setText("Cargo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Correo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 80, 30));
        getContentPane().add(tfcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 170, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setText("Fecha Inicio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 120, 30));

        tffechainicio.setEditable(false);
        getContentPane().add(tffechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 120, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("Estado");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Usuario");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, 30));

        tfcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcuentaActionPerformed(evt);
            }
        });
        getContentPane().add(tfcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 0));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 0));
        jLabel19.setText("Tipo");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 80, 30));

        cbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbLimpiar.setForeground(new java.awt.Color(255, 0, 0));
        cbLimpiar.setText("LIMPIAR");
        cbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(cbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 40));

        cbGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbGuardar.setForeground(new java.awt.Color(255, 0, 0));
        cbGuardar.setText("GUARDAR");
        cbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(cbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 40));

        cbSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSalir.setForeground(new java.awt.Color(255, 0, 0));
        cbSalir.setText("SALIR");
        cbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 130, 40));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 90, 30));

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tecnico", "licenciado", "ingeniero", "biologo", "economista" }));
        getContentPane().add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 90, 30));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 90, 30));

        cbCambiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbCambiar.setText("NEW PASSWORD");
        cbCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCambiarActionPerformed(evt);
            }
        });
        getContentPane().add(cbCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 140, 30));
        getContentPane().add(tfClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/autenticacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean formularioValido(){
        if(tfnombres.getText().equals("") ||
            tfapellidos.getText().equals("") ||
            tfcedula.getText().equals("") ||    
            tfedad.getText().equals("") ||
            tfdireccion.getText().equals("") || 
            tftelefono.getText().equals("") ||
            tfcelular.getText().equals("") ||
            cbsexo.getSelectedItem().equals("") ||
            cbTipo.getSelectedItem().equals("") ||
            cbCargo.getSelectedItem().equals("") ||
            cbEstado.getSelectedItem().equals("") ||
            tfcorreo.getText().equals("") ||
            tfcuenta.getText().equals("") ||
            tfClave.getText().equals("")){
            
           JOptionPane.showMessageDialog(this,"Formulario incompleto","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void limpiarFormulario(){
        tfnombres.setText(null);
        tfapellidos.setText(null);
        tfcedula.setText(null);
        tfedad.setText(null);
        tfdireccion.setText(null);
        tftelefono.setText(null);
        tfcelular.setText(null);
        cbsexo.setSelectedItem(null);
        cbTipo.setSelectedItem(null);
        cbCargo.setSelectedItem(null);
        cbEstado.setSelectedItem(null);
        tfcorreo.setText(null);
        tffechainicio.setText(null);
        tfcuenta.setText(null);
    }
    
    private void cbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_cbLimpiarActionPerformed

    private void cbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuardarActionPerformed
        ConexionBD c = new ConexionBD();
        if(formularioValido()){
            //int id_usuario        = Integer.parseInt(tfid.getText());
            String nombres        = tfnombres.getText();
            String apellidos      = tfapellidos.getText();
            String cedula         = tfcedula.getText();
            int edad              = Integer.parseInt(tfedad.getText());
            String direccion      = tfdireccion.getText();
            String correo         = tfcorreo.getText();
            String telefono       = tftelefono.getText();
            String celular        = tfcelular.getText();
            String sexo           = cbsexo.getSelectedItem().toString();
            String tipo           = (String)cbsexo.getSelectedItem();
            String cargo          = (String)cbCargo.getSelectedItem();
            Date fecha_inicio     = Date.valueOf(tffechainicio.getText());
            String estado         = (String)cbEstado.getSelectedItem();
            String cuenta         = tfcuenta.getText();
            String clave          = tfClave.getText();

            try{
                c.conectar();
                usuario u = new usuario(cuenta, clave, nombres, apellidos, cedula, edad, direccion, telefono, celular, correo, tipo, sexo, cargo, estado, fecha_inicio);
                if(c.ingresarUsuario(u)){
                    JOptionPane.showMessageDialog(this,"Ingreso Exitoso a la base de datos","Validación",JOptionPane.INFORMATION_MESSAGE);
                    frmAutenticacion frm = new frmAutenticacion();
                    frm.setVisible(true);
                    this.dispose();
                }else
                JOptionPane.showMessageDialog(this,"Ingreso Fallido","Validación",JOptionPane.ERROR_MESSAGE);
                c.desconectar();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Ocurrio un problema durante el ingreso","Validación",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbGuardarActionPerformed

    private void cbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"¿DESEA SALIR?","ATENCION",JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            frmPrincipal frm = new frmPrincipal();
            frm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cbSalirActionPerformed

    private void tfcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcuentaActionPerformed

    private void cbCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCambiarActionPerformed
        frmNuevoPassword frm = new frmNuevoPassword();
        frm.setVisible(true);
    }//GEN-LAST:event_cbCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbCambiar;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton cbGuardar;
    private javax.swing.JButton cbLimpiar;
    private javax.swing.JButton cbSalir;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfClave;
    private javax.swing.JFormattedTextField tfapellidos;
    private javax.swing.JFormattedTextField tfcedula;
    private javax.swing.JFormattedTextField tfcelular;
    private javax.swing.JFormattedTextField tfcorreo;
    private javax.swing.JFormattedTextField tfcuenta;
    private javax.swing.JFormattedTextField tfdireccion;
    private javax.swing.JFormattedTextField tfedad;
    private javax.swing.JFormattedTextField tffechainicio;
    private javax.swing.JFormattedTextField tfid;
    private javax.swing.JFormattedTextField tfnombres;
    private javax.swing.JFormattedTextField tftelefono;
    // End of variables declaration//GEN-END:variables
}
