package Formularios;

import Objetos.operador;
import bd.ConexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerson Junqui
 */
public class frmMantenimientoOperador extends javax.swing.JFrame {

    /**
     * Creates new form frmMantenimientoOperador
     */
    public frmMantenimientoOperador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();
        tfDescripcion = new javax.swing.JFormattedTextField();
        cbBuscar = new javax.swing.JButton();
        lista = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbSalir = new javax.swing.JButton();
        cbNuevo = new javax.swing.JButton();
        cbEliminar = new javax.swing.JButton();
        cbEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("MANTENIMIENTO OPERADOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 430, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 590, 20));

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Cedula", "Telefono", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 170, 800, 220));
        getContentPane().add(tfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 280, 30));

        cbBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbBuscar.setForeground(new java.awt.Color(255, 0, 0));
        cbBuscar.setText("BUSCAR");
        cbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(cbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 120, 30));

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Tipo" }));
        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("DESCRIPCIÓN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 140, 30));

        cbSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSalir.setForeground(new java.awt.Color(255, 0, 0));
        cbSalir.setText("SALIR");
        cbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 130, 40));

        cbNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbNuevo.setForeground(new java.awt.Color(255, 0, 0));
        cbNuevo.setText("NUEVO");
        cbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(cbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 130, 40));

        cbEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbEliminar.setForeground(new java.awt.Color(255, 0, 0));
        cbEliminar.setText("ELIMINAR");
        cbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(cbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, 40));

        cbEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbEditar.setForeground(new java.awt.Color(255, 0, 0));
        cbEditar.setText("EDITAR");
        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });
        getContentPane().add(cbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/autenticacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalirActionPerformed
        frmPrincipal ino = new frmPrincipal();
        ino.setVisible(true);
    }//GEN-LAST:event_cbSalirActionPerformed

    private void cbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNuevoActionPerformed
        frmIngresoNuevoOperador ino = new frmIngresoNuevoOperador();
        ino.setVisible(true);
    }//GEN-LAST:event_cbNuevoActionPerformed

    private boolean formularioValido(){
        String tipo = lista.getSelectedItem().toString();
        String descripcion = tfDescripcion.getText();
        if(tipo.equals("Nombre") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar el nombre.","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Cedula") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar la cedula.","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Telefono") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar el telefono","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }else if(tipo.equals("Tipo") && descripcion.equals("")){
                JOptionPane.showMessageDialog(this,"Debe ingresar el tipo","Consulta",JOptionPane.ERROR_MESSAGE);
                return false;
        }
        return true;
    }
    
    public void consultarRegistro(){
        String tipo = lista.getSelectedItem().toString();
        String descripcion = tfDescripcion.getText();        
        //consultar
        try{
            //cunsolta a la base
            try{
                ConexionBD c = new ConexionBD();
                c.conectar();
                ArrayList<operador> registro = c.consultarOperadores("","operador");
                ArrayList<operador> resultado = new ArrayList<operador>();
                //Consultar tipo y descripcion
                if (tipo.equals("Todos")){
                        resultado = registro;
                }else{
                    for (operador emp:registro){
                        if(tipo.equals("Id")&&(descripcion.length()>0)){
                            if(String.valueOf(emp.getId()).equals(descripcion) ){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Nombre")){
                            if(emp.getNombre().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Cedula")){
                            if(emp.getCedula().toUpperCase().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Telefono")){
                            if(emp.getTelefono().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else if(tipo.equals("Tipo")){
                            if(emp.getTipo().contains(descripcion.toUpperCase())){
                                resultado.add(emp);
                            }
                        }else{
                            JOptionPane.showMessageDialog(this,"Descripcion vacia.","Consulta Invalida",JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                    }
                }

                DefaultTableModel dtm = (DefaultTableModel)tbResultado.getModel();
                dtm.setRowCount(0);
                
                //recorriendo base de datos
                for (operador em:resultado){
                    Object[] fila = new Object[5];
                    fila[0] = em.getId();
                    fila[1] = em.getNombre();
                    fila[2] = em.getCedula();
                    fila[3] = em.getTelefono();
                    fila[4] = em.getTipo();
                    dtm.addRow(fila);
                }
            c.desconectar();
            }catch (Exception e){
                System.out.println("error al consultar operadores"+e);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los operadores","Consulta",JOptionPane.ERROR_MESSAGE);
            System.out.println("consulta de registros operadores: "+e);
        }
    }
    
    private void cbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarActionPerformed
        if (formularioValido()){
            consultarRegistro();
        }
    }//GEN-LAST:event_cbBuscarActionPerformed

    private boolean seleccionEliminacionValidaOperador(){
        int n = this.tbResultado.getSelectedRowCount();
        if(n==0){
            JOptionPane.showMessageDialog(this,"Debe seleccionar mínimo un registro para eliminar","Eliminación",JOptionPane.ERROR_MESSAGE);            
            return false;
        }
        int opcion=JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar el/los registros?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(JOptionPane.OK_OPTION==opcion){
            return true;
        }else{
            return false;
        }             
    }
    
    private void cbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEliminarActionPerformed
        ConexionBD c = new ConexionBD();
        if(seleccionEliminacionValidaOperador()){
            int col = 0;
            int fila = tbResultado.getSelectedRow();
            String identificacion = String.valueOf(tbResultado.getValueAt(fila,col));
            
            int id=Integer.valueOf(identificacion);
            System.out.println(id);
            try{
                c.conectar();
                if(c.eliminarOperador(id)){
                    JOptionPane.showMessageDialog(this,"Eliminacion Exitosa","Validación",JOptionPane.INFORMATION_MESSAGE);
                    consultarRegistro();
                }else{
                    JOptionPane.showMessageDialog(this,"Eliminacion Fallida","Validación",JOptionPane.ERROR_MESSAGE);
                }
                c.desconectar();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Ocurrio un problema durante la eliminacion","Validación",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbEliminarActionPerformed

    private boolean seleccionEdicionValidaOperador(){
        int n = tbResultado.getSelectedRowCount();
        if(n==0){
            JOptionPane.showMessageDialog(rootPane,"Debe seleccionar un registro para editar","Edición",JOptionPane.ERROR_MESSAGE);            
            return false;
        }else if(n>1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar sólo un registro para editar","Edición",JOptionPane.ERROR_MESSAGE);                    
            return false;    
        }
        return true;
    }
    
    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        if(seleccionEdicionValidaOperador()){
            //frmEdicionOperador eo = new frmEdicionOperador();
            //eo.setVisible(true);
        }
    }//GEN-LAST:event_cbEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbBuscar;
    private javax.swing.JButton cbEditar;
    private javax.swing.JButton cbEliminar;
    private javax.swing.JButton cbNuevo;
    private javax.swing.JButton cbSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTable tbResultado;
    private javax.swing.JFormattedTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
