package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Jerson Junqui
 */
public class frmMensajeria extends javax.swing.JFrame {

    /**
     * Creates new form frmMensajeria
     */
    public frmMensajeria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMensaje = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbEnviar = new javax.swing.JButton();
        cbSalir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMensaje.setBackground(new java.awt.Color(153, 204, 255));
        PanelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        PanelMensaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("    MENSAJERÍA INTERNA - CAMARONERA MARBETH");
        PanelMensaje.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marcelo Rodriguez", "Vanessa Saraguro" }));
        PanelMensaje.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Darwin Freire" }));
        PanelMensaje.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", " " }));
        PanelMensaje.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("PARA:");
        PanelMensaje.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Oficina");
        PanelMensaje.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Administradores");
        PanelMensaje.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Trabajadores");
        PanelMensaje.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 90, -1));
        PanelMensaje.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 20));
        PanelMensaje.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 20));

        cbEnviar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbEnviar.setText("ENVIAR");
        PanelMensaje.add(cbEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 120, 30));

        cbSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSalir.setText("SALIR");
        cbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalirActionPerformed(evt);
            }
        });
        PanelMensaje.add(cbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 100, 30));
        PanelMensaje.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 390, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PanelMensaje.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 360));

        getContentPane().add(PanelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"¿DESEA REGRESAR A LA VENTANA PRINCIPAL?","ATENCION",JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_cbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMensaje;
    private javax.swing.JButton cbEnviar;
    private javax.swing.JButton cbSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
