/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miCuenta = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mProcesos = new javax.swing.JMenu();
        mAyuda = new javax.swing.JMenu();
        miAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema JuBa 2018 - MI LicRed");

        mArchivo.setText("Archivo");

        miCuenta.setText("Cuenta");
        mArchivo.add(miCuenta);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        jMenuBar1.add(mArchivo);

        mMantenimiento.setText("Mantenimiento");
        jMenuBar1.add(mMantenimiento);

        mProcesos.setText("Procesos");
        jMenuBar1.add(mProcesos);

        mAyuda.setText("Ayuda");

        miAcercaDe.setText("Acerca De...");
        miAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaDeActionPerformed(evt);
            }
        });
        mAyuda.add(miAcercaDe);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaDeActionPerformed
        // TODO add your handling code here:
        frmAcercaDe acd = new frmAcercaDe();
        acd.setVisible(true);
    }//GEN-LAST:event_miAcercaDeActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        int opt1= JOptionPane.showConfirmDialog(this,"¿Esta Seguro de que desea Salir?","Cerrar Sesion",JOptionPane.YES_NO_OPTION);
        if(opt1==0){
            this.dispose();
            frmAutenticacion fau = new frmAutenticacion();
            fau.setVisible(true);           
            //System.exit(0);
        }
    }//GEN-LAST:event_miSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenu mProcesos;
    private javax.swing.JMenuItem miAcercaDe;
    private javax.swing.JMenuItem miCuenta;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
