/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Objetos.*;
import bd.ConexionBD;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     * @param empresa
     */
    public frmPrincipal(empresa empresa, usuario u) {
        initComponents();
        
        lbUsuario.setText(u.getCuenta());
        System.out.println(lbUsuario.getText());
        
        tfnombre.setText(empresa.getNombre());
        tfruc.setText(empresa.getRuc());
        tfdireccion.setText(empresa.getDireccion());
        tfdireccionplanta.setText(empresa.getDireccion_planta());
        tftelefono.setText(empresa.getTelefono());
        tfcorreo.setText(empresa.getCorreo());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        tfnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfruc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdireccionplanta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tftelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miCuenta = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mUsuario = new javax.swing.JMenuItem();
        mEmpresa = new javax.swing.JMenuItem();
        mAlimento = new javax.swing.JMenuItem();
        mPiscina = new javax.swing.JMenuItem();
        mProducto = new javax.swing.JMenuItem();
        mOperador = new javax.swing.JMenuItem();
        mProcesos = new javax.swing.JMenu();
        mEvento = new javax.swing.JMenuItem();
        mTablero = new javax.swing.JMenu();
        mAyuda = new javax.swing.JMenu();
        miAcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema JuBa 2018 - MI LicRed");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfnombre.setEditable(false);
        getContentPane().add(tfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Empresa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        tfruc.setEditable(false);
        getContentPane().add(tfruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("RUC:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        tfdireccion.setEditable(false);
        getContentPane().add(tfdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Dirección:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        tfdireccionplanta.setEditable(false);
        getContentPane().add(tfdireccionplanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 210, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Dirección Planta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        tftelefono.setEditable(false);
        tftelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(tftelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        tfcorreo.setEditable(false);
        tfcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcorreoActionPerformed(evt);
            }
        });
        getContentPane().add(tfcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 114, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dos.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 300, 170));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("PROCESO DE PRODUCCIÓN PARA LARVAS DE CAMARÓN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 730, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tres.jpeg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 170));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/siete.jpeg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 170));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cuatro.jpeg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 300, 170));

        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seis.jpeg"))); // NOI18N
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 300, 170));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cinco.jpeg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 300, 170));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/uno.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        mArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/esquina.jpg"))); // NOI18N
        mArchivo.setText("Archivo");

        miCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_small.png"))); // NOI18N
        miCuenta.setText("Cuenta");
        miCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCuentaActionPerformed(evt);
            }
        });
        mArchivo.add(miCuenta);

        miSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        jMenuBar1.add(mArchivo);

        mMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mantenimiento.png"))); // NOI18N
        mMantenimiento.setText("Mantenimiento");

        mUsuario.setText("Usuario");
        mMantenimiento.add(mUsuario);

        mEmpresa.setText("Empresa");
        mMantenimiento.add(mEmpresa);

        mAlimento.setText("Alimento");
        mMantenimiento.add(mAlimento);

        mPiscina.setText("Piscina");
        mMantenimiento.add(mPiscina);

        mProducto.setText("Producto");
        mMantenimiento.add(mProducto);

        mOperador.setText("Operadores");
        mMantenimiento.add(mOperador);

        jMenuBar1.add(mMantenimiento);

        mProcesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/procesos.png"))); // NOI18N
        mProcesos.setText("Procesos");

        mEvento.setText("Evento");
        mProcesos.add(mEvento);

        jMenuBar1.add(mProcesos);

        mTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mensajeria.png"))); // NOI18N
        mTablero.setText("Mensajería");
        jMenuBar1.add(mTablero);

        mAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/consultar.jpg"))); // NOI18N
        mAyuda.setText("Ayuda");

        miAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/espol.png"))); // NOI18N
        miAcercaDe.setText("Acerca De...");
        miAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaDeActionPerformed(evt);
            }
        });
        mAyuda.add(miAcercaDe);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaDeActionPerformed
        // TODO add your handling code here:
        frmAcercaDe acd = new frmAcercaDe();
        acd.setVisible(true);
    }//GEN-LAST:event_miAcercaDeActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        int opt1= JOptionPane.showConfirmDialog(this,"¿Esta Seguro de que desea Salir?","Cerrar Sesion",JOptionPane.YES_NO_OPTION);
        if(opt1==0){
            this.dispose();
            //frmAutenticacion fau = new frmAutenticacion();
            //fau.setVisible(true);           
            //System.exit(0);
        }
    }//GEN-LAST:event_miSalirActionPerformed

    private void tftelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefonoActionPerformed

    private void tfcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcorreoActionPerformed

    private void miCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCuentaActionPerformed
        // TODO add your handling code here:
        ConexionBD c = new ConexionBD();
        try{
            c.conectar();
            usuario u = c.obtenerDatosUsuario(lbUsuario.getText());
            frmCuenta cuenta = new frmCuenta(u);
            cuenta.setVisible(true);
        }catch(Exception e){
            System.out.println("error al cargar usuario"+e);
        }   
        c.desconectar();
    }//GEN-LAST:event_miCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenuItem mAlimento;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem mEmpresa;
    private javax.swing.JMenuItem mEvento;
    private javax.swing.JMenu mMantenimiento;
    private javax.swing.JMenuItem mOperador;
    private javax.swing.JMenuItem mPiscina;
    private javax.swing.JMenu mProcesos;
    private javax.swing.JMenuItem mProducto;
    private javax.swing.JMenu mTablero;
    private javax.swing.JMenuItem mUsuario;
    private javax.swing.JMenuItem miAcercaDe;
    private javax.swing.JMenuItem miCuenta;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JLabel seis;
    private javax.swing.JTextField tfcorreo;
    private javax.swing.JTextField tfdireccion;
    private javax.swing.JTextField tfdireccionplanta;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfruc;
    private javax.swing.JTextField tftelefono;
    // End of variables declaration//GEN-END:variables
}
