/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Objetos.*;
import bd.ConexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmSeleccionarEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form frmSeleccionarEmpresa
     * @param u
     * @param usuario
     */
    public frmSeleccionarEmpresa(usuario u) {
        initComponents();
        //datos del usuario
        System.out.println("Datos usuario: "+u.getCuenta());
        
        tfcuenta_usuario.setText(u.getCuenta());
        
        //cargar empresas del usuario
        //cargando datos de cliente a editar
        ConexionBD c = new ConexionBD();
        try{
            c.conectar();
            ArrayList<empresa> emps = c.cargarEmpresas(u.getId());
            c.desconectar();
            for (empresa emp:emps){
                String item = emp.getNombre();
                cbEmpresa.addItem(item);
                System.out.println(item);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los datos del registro","Cargar Empresas",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbEmpresa = new javax.swing.JComboBox<>();
        btSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfcuenta_usuario = new javax.swing.JTextField();
        cbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selección de Empresa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 64, 162, 32));

        btSeleccionar.setText("Seleccionar");
        btSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 114, -1, -1));

        jLabel1.setText("Empresa/s:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 73, -1, -1));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 41, -1, -1));

        tfcuenta_usuario.setEditable(false);
        getContentPane().add(tfcuenta_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 38, 162, -1));

        cbSalir.setText("salir");
        cbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 0, 60, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionarActionPerformed
        // TODO add your handling code here:
        ConexionBD c = new ConexionBD();
        try{
            c.conectar();
            usuario u = c.obtenerDatosUsuario(tfcuenta_usuario.getText());
            empresa e = c.obtenerDatosEmpresa(cbEmpresa.getSelectedItem().toString());
            c.desconectar();
            frmPrincipal p = new frmPrincipal(e, u);
            p.setVisible(true);
            //this.dispose();
        }catch(Exception ex){
            System.out.println(ex);
        }        
    }//GEN-LAST:event_btSeleccionarActionPerformed

    private void cbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"¿DESEA SALIR?","ATENCION",JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            frmAutenticacion frm = new frmAutenticacion();
            frm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cbSalirActionPerformed
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSeleccionar;
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JButton cbSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfcuenta_usuario;
    // End of variables declaration//GEN-END:variables
}
