package Formularios;

import Objetos.*;
import bd.ConexionBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class frmSeleccionarEmpresas extends javax.swing.JFrame {

    /**
     * Creates new form frmSeleccionarEmpresas
     */
    public frmSeleccionarEmpresas(usuario u) {
        initComponents();
        
        System.out.println("Datos usuario: "+u.getCuenta());
        
        tfusuario.setText(u.getCuenta());
        /*
        cargar empresas del usuario
        cargando datos de cliente a editar
        otras empresas:
        Marbeth, Pescasol, Pescarasa, SeaMar
        */
        ConexionBD c = new ConexionBD();
        try{
            c.conectar();
            ArrayList<empresa> emps = c.cargarEmpresas(u.getId());
            c.desconectar();
            for (empresa emp:emps){
                String item = emp.getNombre();
                cbempresas.addItem(item);
                System.out.println(item);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrió un error al consultar los datos del registro","Cargar Empresas",JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbempresas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cbSalir = new javax.swing.JButton();
        btSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        tfusuario.setEditable(false);
        getContentPane().add(tfusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Empresa/s:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        cbempresas.setToolTipText("");
        getContentPane().add(cbempresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbSalir.setForeground(new java.awt.Color(255, 0, 0));
        cbSalir.setText("Salir");
        cbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 130, 40));

        btSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSeleccionar.setForeground(new java.awt.Color(255, 0, 0));
        btSeleccionar.setText("Seleccionar");
        btSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionarActionPerformed
        // TODO add your handling code here:
        ConexionBD c = new ConexionBD();
        try{
            c.conectar();
            usuario u = c.obtenerDatosUsuario(tfusuario.getText());
            empresa e = c.obtenerDatosEmpresa(cbempresas.getSelectedItem().toString());
            c.desconectar();
            if(u.getTipo().equals("administrador")){
                frmPrincipal p = new frmPrincipal(e, u);
                p.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"El usuario no es Admnistrador","Atención",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btSeleccionarActionPerformed

    private void cbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Atención",JOptionPane.YES_NO_OPTION);
        if(opcion==0){
            frmAutenticacion aut = new frmAutenticacion();
            aut.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSeleccionar;
    private javax.swing.JButton cbSalir;
    private javax.swing.JComboBox<String> cbempresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfusuario;
    // End of variables declaration//GEN-END:variables
}
